import type {TVSCreditEMIScene} from './types';

export const TVS_CREDIT_EMI_SCENES: TVSCreditEMIScene[] = [
  {
    kind: 'intro',
    eyebrow: 'Important Update',
    title: 'Hi {{customerName}}',
    subtitle: 'Your EMI payment of ₹{{tos}} is due.',
    relativeDuration: { en: 0.140, hi: 0.140 },
  },
  {
    kind: 'text-only',
    method: 1,
    eyebrow: 'Method 1',
    title: 'Payment Link',
    subtitle: 'A secure link has been sent to you on WhatsApp and SMS.',
    relativeDuration: { en: 0.035, hi: 0.035 },
  },
  {
    kind: 'fullscreen-image',
    method: 1,
    image: 'paynow_whatsapp.png',
    caption: 'Click the "Pay Now" button on WhatsApp',
    relativeDuration: { en: 0.045, hi: 0.045 },
  },
  {
    kind: 'fullscreen-image',
    method: 1,
    image: 'link_sms.png',
    caption: 'Or click the link shared via SMS',
    relativeDuration: { en: 0.060, hi: 0.060 },
  },
  {
    kind: 'fullscreen-image',
    method: 1,
    image: 'click_andpay.png',
    caption: 'Review details and tap "Proceed to Pay"',
    relativeDuration: { en: 0.090, hi: 0.090 },
  },
  {
    kind: 'text-only',
    method: 2,
    eyebrow: 'Method 2',
    title: 'UPI / Payment Apps',
    subtitle: 'Pay conveniently using PhonePe, Google Pay, or any UPI app.',
    relativeDuration: { en: 0.045, hi: 0.045 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'upi_app.png',
    caption: 'Open PhonePe or Google Pay',
    relativeDuration: { en: 0.075, hi: 0.075 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'open_app_search.png',
    caption: 'Go to Repayment and search for payment option',
    relativeDuration: { en: 0.075, hi: 0.075 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'enter_lan.png',
    caption: 'Enter LAN and complete payment using UPI PIN',
    relativeDuration: { en: 0.045, hi: 0.045 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'payment_success.png',
    caption: 'Wait for successful payment confirmation',
    relativeDuration: { en: 0.040, hi: 0.040 },
  },
  {
    kind: 'text-only',
    method: 3,
    eyebrow: 'Method 3',
    title: 'Online Digital Kendra',
    subtitle: 'Visit your nearest Online Digital Kendra to deposit your EMI amount.',
    relativeDuration: { en: 0.045, hi: 0.045 },
  },
  {
    kind: 'fullscreen-image',
    method: 3,
    image: 'shop_visit.png',
    caption: 'Visit nearest Online Digital Kendra to deposit cash',
    relativeDuration: { en: 0.050, hi: 0.050 },
  },
  {
    kind: 'final',
    eyebrow: 'Final Reminder',
    title: 'Pay Today',
    subtitle: 'Contact {{contactDetails}} immediately to discuss options and avoid charges.',
    relativeDuration: { en: 0.260, hi: 0.260 },
  },
];
